# listing_type: "sale" (venta) | "rent" (alquiler)
# price en alquiler = soles/mes
# Imágenes: Unsplash (sin API key, rotadas por tipo de propiedad)

_IMG = {
    "depa": [
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1599427303058-f9aa1e8da854?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=80&auto=format",
    ],
    "casa": [
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1605276374104-9bbc378785af?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80&auto=format",
    ],
    "terreno": [
        "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1416331329427-3b3b6a64c950?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?w=600&q=80&auto=format",
    ],
    "oficina": [
        "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=600&q=80&auto=format",
    ],
    "local": [
        "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600&q=80&auto=format",
        "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=600&q=80&auto=format",
    ],
}


def _img(tipo: str, idx: int) -> str:
    pool = _IMG.get(tipo, _IMG["depa"])
    return pool[idx % len(pool)]


MOCK_PROPERTIES = [
    # ══════════════════════════════════════════════════════════════════
    # DEPARTAMENTOS EN VENTA (25)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Departamento exclusivo frente Zona Golf", "price": 520000, "area_m2": 140, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-001", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Depa moderno Zona Golf con balcón panorámico", "price": 460000, "area_m2": 120, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-002", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento 2 dorm cerca al malecón Victor Larco", "price": 310000, "area_m2": 90, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-003", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Departamento premium Urb. California Victor Larco", "price": 395000, "area_m2": 105, "zone": "Urb. California", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-004", "source_name": "mock", "image_url": _img("depa", 3)},
    {"title": "Departamento de lujo con vista al golf", "price": 680000, "area_m2": 180, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-005", "source_name": "mock", "image_url": _img("depa", 4)},
    {"title": "Departamento Trujillo Centro bien ubicado", "price": 220000, "area_m2": 70, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-006", "source_name": "mock", "image_url": _img("depa", 5)},
    {"title": "Flat moderno en el Centro de Trujillo", "price": 185000, "area_m2": 60, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-007", "source_name": "mock", "image_url": _img("depa", 6)},
    {"title": "Departamento nuevo Huanchaco con vista al mar", "price": 285000, "area_m2": 82, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-008", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Departamento frente playa Huanchaco 3 dorm", "price": 340000, "area_m2": 100, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-009", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento económico La Esperanza 1 dorm", "price": 78000, "area_m2": 48, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "departamento", "bedrooms": 1, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-010", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Departamento La Esperanza 2 dorm accesible", "price": 105000, "area_m2": 62, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-011", "source_name": "mock", "image_url": _img("depa", 3)},
    {"title": "Departamento en El Porvenir con garage", "price": 120000, "area_m2": 68, "zone": "Zona Este", "district": "El Porvenir", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-012", "source_name": "mock", "image_url": _img("depa", 4)},
    {"title": "Departamento en Salaverry cerca al puerto", "price": 145000, "area_m2": 65, "zone": "Zona Sur", "district": "Salaverry", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-013", "source_name": "mock", "image_url": _img("depa", 5)},
    {"title": "Penthouse Zona Golf con terraza privada", "price": 850000, "area_m2": 220, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 4, "bathrooms": 4, "parking": 3, "listing_type": "sale", "source_url": "mock://prop-014", "source_name": "mock", "image_url": _img("depa", 6)},
    {"title": "Departamento Moche moderno y nuevo", "price": 160000, "area_m2": 72, "zone": "Zona Sur", "district": "Moche", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-015", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Depa Florencia de Mora precio de oportunidad", "price": 90000, "area_m2": 55, "zone": "Zona Norte", "district": "Florencia de Mora", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-016", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento Laredo con jardín compartido", "price": 175000, "area_m2": 78, "zone": "Zona Este", "district": "Laredo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-017", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Flat ejecutivo Trujillo Centro ideal inversión", "price": 240000, "area_m2": 75, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-018", "source_name": "mock", "image_url": _img("depa", 3)},
    {"title": "Departamento Buenos Aires vista al océano", "price": 210000, "area_m2": 68, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-019", "source_name": "mock", "image_url": _img("depa", 4)},
    {"title": "Departamento amoblado Urb. El Golf", "price": 490000, "area_m2": 130, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-020", "source_name": "mock", "image_url": _img("depa", 5)},
    {"title": "Departamento seminuevo Victor Larco 2 dorm", "price": 275000, "area_m2": 85, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-021", "source_name": "mock", "image_url": _img("depa", 6)},
    {"title": "Departamento 1er piso con patio propio Trujillo", "price": 195000, "area_m2": 80, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-022", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Depa en edificio moderno Salaverry", "price": 165000, "area_m2": 70, "zone": "Zona Sur", "district": "Salaverry", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-023", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento Huanchaco piso alto con balcón", "price": 298000, "area_m2": 88, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-024", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Departamento en Urb. Primavera Trujillo 3 dorm", "price": 255000, "area_m2": 92, "zone": "Urb. Primavera", "district": "Trujillo", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-025", "source_name": "mock", "image_url": _img("depa", 3)},

    # ══════════════════════════════════════════════════════════════════
    # CASAS EN VENTA (25)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Casa exclusiva frente al Country Club Trujillo", "price": 580000, "area_m2": 220, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-026", "source_name": "mock", "image_url": _img("casa", 0)},
    {"title": "Casa con piscina y jardín en Victor Larco", "price": 480000, "area_m2": 200, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-027", "source_name": "mock", "image_url": _img("casa", 1)},
    {"title": "Casa moderna en Urb. California Victor Larco", "price": 420000, "area_m2": 180, "zone": "Urb. California", "district": "Victor Larco", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-028", "source_name": "mock", "image_url": _img("casa", 2)},
    {"title": "Casa de playa con vista al mar Huanchaco", "price": 400000, "area_m2": 160, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-029", "source_name": "mock", "image_url": _img("casa", 3)},
    {"title": "Casa amplia en Huanchaco zona residencial", "price": 320000, "area_m2": 150, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-030", "source_name": "mock", "image_url": _img("casa", 4)},
    {"title": "Casa en Buenos Aires frente al mar", "price": 250000, "area_m2": 130, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-031", "source_name": "mock", "image_url": _img("casa", 5)},
    {"title": "Casa familiar en Buenos Aires a 2 cuadras playa", "price": 195000, "area_m2": 110, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-032", "source_name": "mock", "image_url": _img("casa", 6)},
    {"title": "Casa con huerto y áreas verdes en Laredo", "price": 200000, "area_m2": 180, "zone": "Zona Este", "district": "Laredo", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-033", "source_name": "mock", "image_url": _img("casa", 7)},
    {"title": "Casa en Moche cerca Huaca del Sol", "price": 195000, "area_m2": 140, "zone": "Zona Sur", "district": "Moche", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-034", "source_name": "mock", "image_url": _img("casa", 8)},
    {"title": "Casa amplia Moche con techo propio", "price": 155000, "area_m2": 120, "zone": "Zona Sur", "district": "Moche", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-035", "source_name": "mock", "image_url": _img("casa", 9)},
    {"title": "Casa en La Esperanza sector 5 bien ubicada", "price": 130000, "area_m2": 100, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-036", "source_name": "mock", "image_url": _img("casa", 0)},
    {"title": "Casa en La Esperanza 2 pisos semi-nueva", "price": 150000, "area_m2": 130, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "casa", "bedrooms": 4, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-037", "source_name": "mock", "image_url": _img("casa", 1)},
    {"title": "Casa en El Porvenir precio accesible", "price": 110000, "area_m2": 90, "zone": "Zona Este", "district": "El Porvenir", "property_type": "casa", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-038", "source_name": "mock", "image_url": _img("casa", 2)},
    {"title": "Casa El Porvenir ampliable con terreno extra", "price": 140000, "area_m2": 160, "zone": "Zona Este", "district": "El Porvenir", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-039", "source_name": "mock", "image_url": _img("casa", 3)},
    {"title": "Casa de lujo con sala de cine Zona Golf", "price": 750000, "area_m2": 280, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "casa", "bedrooms": 5, "bathrooms": 4, "parking": 3, "listing_type": "sale", "source_url": "mock://prop-040", "source_name": "mock", "image_url": _img("casa", 4)},
    {"title": "Casa con piscina en urbanización privada Trujillo", "price": 380000, "area_m2": 190, "zone": "Urb. Primavera", "district": "Trujillo", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-041", "source_name": "mock", "image_url": _img("casa", 5)},
    {"title": "Casa en el Centro de Trujillo en esquina", "price": 290000, "area_m2": 150, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "casa", "bedrooms": 4, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-042", "source_name": "mock", "image_url": _img("casa", 6)},
    {"title": "Casa nueva en Salaverry cerca al mar", "price": 230000, "area_m2": 135, "zone": "Zona Sur", "district": "Salaverry", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-043", "source_name": "mock", "image_url": _img("casa", 7)},
    {"title": "Casa en Florencia de Mora 3 dorm económica", "price": 118000, "area_m2": 95, "zone": "Zona Norte", "district": "Florencia de Mora", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-044", "source_name": "mock", "image_url": _img("casa", 8)},
    {"title": "Casa esquinera doble frente La Esperanza", "price": 175000, "area_m2": 148, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "casa", "bedrooms": 4, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-045", "source_name": "mock", "image_url": _img("casa", 9)},
    {"title": "Casa Victor Larco con jardín y cochera doble", "price": 355000, "area_m2": 175, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-046", "source_name": "mock", "image_url": _img("casa", 0)},
    {"title": "Casa 2 pisos Urb. Santa Inés Trujillo", "price": 310000, "area_m2": 165, "zone": "Urb. Santa Inés", "district": "Trujillo", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-047", "source_name": "mock", "image_url": _img("casa", 1)},
    {"title": "Casa con barbacoa Huanchaco muy agradable", "price": 275000, "area_m2": 140, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-048", "source_name": "mock", "image_url": _img("casa", 2)},
    {"title": "Casa Moche 4 dorm con cuarto de servicio", "price": 220000, "area_m2": 160, "zone": "Zona Sur", "district": "Moche", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-049", "source_name": "mock", "image_url": _img("casa", 3)},
    {"title": "Casa de campo en Laredo con árboles frutales", "price": 185000, "area_m2": 200, "zone": "Zona Este", "district": "Laredo", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-050", "source_name": "mock", "image_url": _img("casa", 4)},

    # ══════════════════════════════════════════════════════════════════
    # TERRENOS EN VENTA (12)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Terreno Buenos Aires frente a la playa 250 m2", "price": 180000, "area_m2": 250, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-051", "source_name": "mock", "image_url": _img("terreno", 0)},
    {"title": "Terreno en La Esperanza habilitado 200 m2", "price": 95000, "area_m2": 200, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-052", "source_name": "mock", "image_url": _img("terreno", 1)},
    {"title": "Terreno esquinero El Porvenir 300 m2", "price": 110000, "area_m2": 300, "zone": "Zona Este", "district": "El Porvenir", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-053", "source_name": "mock", "image_url": _img("terreno", 2)},
    {"title": "Terreno industrial Salaverry zona portuaria", "price": 350000, "area_m2": 500, "zone": "Zona Industrial", "district": "Salaverry", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-054", "source_name": "mock", "image_url": _img("terreno", 3)},
    {"title": "Terreno en Huanchaco ideal para construcción", "price": 220000, "area_m2": 350, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-055", "source_name": "mock", "image_url": _img("terreno", 0)},
    {"title": "Terreno habilitado Moche 180 m2 servicios completos", "price": 85000, "area_m2": 180, "zone": "Zona Sur", "district": "Moche", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-056", "source_name": "mock", "image_url": _img("terreno", 1)},
    {"title": "Terreno en Laredo para proyecto agroindustrial", "price": 280000, "area_m2": 1200, "zone": "Zona Este", "district": "Laredo", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-057", "source_name": "mock", "image_url": _img("terreno", 2)},
    {"title": "Terreno Victor Larco cerca al golf 160 m2", "price": 420000, "area_m2": 160, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-058", "source_name": "mock", "image_url": _img("terreno", 3)},
    {"title": "Terreno comercial Trujillo Centro avenida principal", "price": 500000, "area_m2": 240, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-059", "source_name": "mock", "image_url": _img("terreno", 0)},
    {"title": "Terreno Florencia de Mora 120 m2 precio justo", "price": 55000, "area_m2": 120, "zone": "Zona Norte", "district": "Florencia de Mora", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-060", "source_name": "mock", "image_url": _img("terreno", 1)},
    {"title": "Terreno Buenos Aires 400 m2 con frente a dos calles", "price": 260000, "area_m2": 400, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-061", "source_name": "mock", "image_url": _img("terreno", 2)},
    {"title": "Terreno Salaverry zona residencial 220 m2", "price": 130000, "area_m2": 220, "zone": "Zona Sur", "district": "Salaverry", "property_type": "terreno", "bedrooms": None, "bathrooms": None, "parking": None, "listing_type": "sale", "source_url": "mock://prop-062", "source_name": "mock", "image_url": _img("terreno", 3)},

    # ══════════════════════════════════════════════════════════════════
    # OFICINAS EN VENTA (6)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Oficina ejecutiva Centro Trujillo piso 5", "price": 160000, "area_m2": 55, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-063", "source_name": "mock", "image_url": _img("oficina", 0)},
    {"title": "Oficina premium Zona Golf con sala de reuniones", "price": 280000, "area_m2": 90, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "oficina", "bedrooms": None, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-064", "source_name": "mock", "image_url": _img("oficina", 1)},
    {"title": "Oficina corporativa Victor Larco open space", "price": 195000, "area_m2": 70, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-065", "source_name": "mock", "image_url": _img("oficina", 2)},
    {"title": "Piso de oficinas Trujillo 120 m2 con terraza", "price": 320000, "area_m2": 120, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "oficina", "bedrooms": None, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-066", "source_name": "mock", "image_url": _img("oficina", 3)},
    {"title": "Oficina Salaverry zona empresarial nueva", "price": 145000, "area_m2": 60, "zone": "Zona Sur", "district": "Salaverry", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-067", "source_name": "mock", "image_url": _img("oficina", 0)},
    {"title": "Oficina Moche parque industrial moderno", "price": 120000, "area_m2": 48, "zone": "Zona Sur", "district": "Moche", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "sale", "source_url": "mock://prop-068", "source_name": "mock", "image_url": _img("oficina", 1)},

    # ══════════════════════════════════════════════════════════════════
    # LOCALES COMERCIALES EN VENTA (7)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Local comercial en avenida principal Trujillo", "price": 380000, "area_m2": 150, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-069", "source_name": "mock", "image_url": _img("local", 0)},
    {"title": "Local en galería Centro Trujillo con alta circulación", "price": 95000, "area_m2": 35, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-070", "source_name": "mock", "image_url": _img("local", 1)},
    {"title": "Local esquinero El Porvenir 200 m2 depósito", "price": 145000, "area_m2": 200, "zone": "Zona Este", "district": "El Porvenir", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 1, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-071", "source_name": "mock", "image_url": _img("local", 2)},
    {"title": "Local Victor Larco ideal restaurante 180 m2", "price": 420000, "area_m2": 180, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 2, "parking": 3, "listing_type": "sale", "source_url": "mock://prop-072", "source_name": "mock", "image_url": _img("local", 0)},
    {"title": "Local La Esperanza zona comercial 100 m2", "price": 80000, "area_m2": 100, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 1, "parking": 0, "listing_type": "sale", "source_url": "mock://prop-073", "source_name": "mock", "image_url": _img("local", 1)},
    {"title": "Local Huanchaco zona turística frente playa", "price": 290000, "area_m2": 120, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 2, "parking": 2, "listing_type": "sale", "source_url": "mock://prop-074", "source_name": "mock", "image_url": _img("local", 2)},
    {"title": "Local industrial Salaverry 300 m2 con almacén", "price": 480000, "area_m2": 300, "zone": "Zona Industrial", "district": "Salaverry", "property_type": "local_comercial", "bedrooms": None, "bathrooms": 2, "parking": 5, "listing_type": "sale", "source_url": "mock://prop-075", "source_name": "mock", "image_url": _img("local", 0)},

    # ══════════════════════════════════════════════════════════════════
    # DEPARTAMENTOS EN ALQUILER (15)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Departamento amoblado Zona Golf — alquiler", "price": 3500, "area_m2": 110, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-001", "source_name": "mock", "image_url": _img("depa", 4)},
    {"title": "Departamento en Victor Larco 2 dorm — alquiler", "price": 2200, "area_m2": 80, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-002", "source_name": "mock", "image_url": _img("depa", 5)},
    {"title": "Departamento Centro Trujillo 2 dorm — alquiler", "price": 1400, "area_m2": 60, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-003", "source_name": "mock", "image_url": _img("depa", 6)},
    {"title": "Depa amoblado Huanchaco vista al mar — alquiler", "price": 2500, "area_m2": 75, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-004", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Departamento La Esperanza económico — alquiler", "price": 800, "area_m2": 45, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "departamento", "bedrooms": 1, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-005", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento Golf 3 dorm amoblado lujo — alquiler", "price": 4200, "area_m2": 140, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 3, "parking": 2, "listing_type": "rent", "source_url": "mock://rent-006", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Flat ejecutivo Trujillo Centro — alquiler", "price": 1800, "area_m2": 65, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-007", "source_name": "mock", "image_url": _img("depa", 3)},
    {"title": "Departamento El Porvenir 2 dorm — alquiler", "price": 950, "area_m2": 55, "zone": "Zona Este", "district": "El Porvenir", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-008", "source_name": "mock", "image_url": _img("depa", 4)},
    {"title": "Departamento Salaverry con garage — alquiler", "price": 1300, "area_m2": 68, "zone": "Zona Sur", "district": "Salaverry", "property_type": "departamento", "bedrooms": 2, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-009", "source_name": "mock", "image_url": _img("depa", 5)},
    {"title": "Departamento Moche nuevo moderno — alquiler", "price": 1600, "area_m2": 70, "zone": "Zona Sur", "district": "Moche", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-010", "source_name": "mock", "image_url": _img("depa", 6)},
    {"title": "Departamento Huanchaco zona tranquila — alquiler", "price": 2100, "area_m2": 78, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "departamento", "bedrooms": 2, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-011", "source_name": "mock", "image_url": _img("depa", 0)},
    {"title": "Flat 1 dorm La Esperanza estudiantes — alquiler", "price": 600, "area_m2": 38, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "departamento", "bedrooms": 1, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-012", "source_name": "mock", "image_url": _img("depa", 1)},
    {"title": "Departamento Victor Larco semi-amoblado — alquiler", "price": 2800, "area_m2": 95, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-013", "source_name": "mock", "image_url": _img("depa", 2)},
    {"title": "Departamento Buenos Aires playa temporada — alquiler", "price": 3200, "area_m2": 82, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "departamento", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-014", "source_name": "mock", "image_url": _img("depa", 3)},
    {"title": "Flat Trujillo Centro pequeño y económico — alquiler", "price": 1100, "area_m2": 50, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "departamento", "bedrooms": 1, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-015", "source_name": "mock", "image_url": _img("depa", 4)},

    # ══════════════════════════════════════════════════════════════════
    # CASAS EN ALQUILER (10)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Casa amoblada en Victor Larco 4 dorm — alquiler", "price": 4500, "area_m2": 180, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "rent", "source_url": "mock://rent-016", "source_name": "mock", "image_url": _img("casa", 5)},
    {"title": "Casa frente al mar Huanchaco 3 dorm — alquiler", "price": 3000, "area_m2": 140, "zone": "Zona Playera", "district": "Huanchaco", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-017", "source_name": "mock", "image_url": _img("casa", 6)},
    {"title": "Casa en El Porvenir 2 dorm con patio — alquiler", "price": 1200, "area_m2": 90, "zone": "Zona Este", "district": "El Porvenir", "property_type": "casa", "bedrooms": 2, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-018", "source_name": "mock", "image_url": _img("casa", 7)},
    {"title": "Casa La Esperanza familiar espaciosa — alquiler", "price": 1500, "area_m2": 110, "zone": "Zona Norte", "district": "La Esperanza", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-019", "source_name": "mock", "image_url": _img("casa", 8)},
    {"title": "Casa Zona Golf amoblada premium — alquiler", "price": 6500, "area_m2": 250, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "casa", "bedrooms": 5, "bathrooms": 4, "parking": 3, "listing_type": "rent", "source_url": "mock://rent-020", "source_name": "mock", "image_url": _img("casa", 9)},
    {"title": "Casa Moche tranquila con jardín — alquiler", "price": 1800, "area_m2": 130, "zone": "Zona Sur", "district": "Moche", "property_type": "casa", "bedrooms": 3, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-021", "source_name": "mock", "image_url": _img("casa", 0)},
    {"title": "Casa Salaverry pequeña ideal pareja — alquiler", "price": 1400, "area_m2": 85, "zone": "Zona Sur", "district": "Salaverry", "property_type": "casa", "bedrooms": 2, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-022", "source_name": "mock", "image_url": _img("casa", 1)},
    {"title": "Casa Trujillo Centro 4 dorm gran ubicación — alquiler", "price": 2500, "area_m2": 160, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "casa", "bedrooms": 4, "bathrooms": 2, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-023", "source_name": "mock", "image_url": _img("casa", 2)},
    {"title": "Casa Buenos Aires playa temporada alta — alquiler", "price": 4000, "area_m2": 150, "zone": "Zona Playera", "district": "Buenos Aires", "property_type": "casa", "bedrooms": 4, "bathrooms": 3, "parking": 2, "listing_type": "rent", "source_url": "mock://rent-024", "source_name": "mock", "image_url": _img("casa", 3)},
    {"title": "Casa Florencia de Mora económica 3 dorm — alquiler", "price": 1100, "area_m2": 100, "zone": "Zona Norte", "district": "Florencia de Mora", "property_type": "casa", "bedrooms": 3, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-025", "source_name": "mock", "image_url": _img("casa", 4)},

    # ══════════════════════════════════════════════════════════════════
    # OFICINAS EN ALQUILER (5)
    # ══════════════════════════════════════════════════════════════════
    {"title": "Oficina en Trujillo Centro bien equipada — alquiler", "price": 1800, "area_m2": 50, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-026", "source_name": "mock", "image_url": _img("oficina", 2)},
    {"title": "Oficina Zona Golf reuniones y coworking — alquiler", "price": 3200, "area_m2": 80, "zone": "Zona Golf", "district": "Victor Larco", "property_type": "oficina", "bedrooms": None, "bathrooms": 2, "parking": 2, "listing_type": "rent", "source_url": "mock://rent-027", "source_name": "mock", "image_url": _img("oficina", 3)},
    {"title": "Consultorio/oficina Victor Larco — alquiler", "price": 1500, "area_m2": 40, "zone": "Zona Residencial", "district": "Victor Larco", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-028", "source_name": "mock", "image_url": _img("oficina", 0)},
    {"title": "Oficina moderna Salaverry parque empresarial — alquiler", "price": 1200, "area_m2": 45, "zone": "Zona Sur", "district": "Salaverry", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 1, "listing_type": "rent", "source_url": "mock://rent-029", "source_name": "mock", "image_url": _img("oficina", 1)},
    {"title": "Piso compartido coworking Centro Trujillo — alquiler", "price": 900, "area_m2": 30, "zone": "Trujillo Centro", "district": "Trujillo", "property_type": "oficina", "bedrooms": None, "bathrooms": 1, "parking": 0, "listing_type": "rent", "source_url": "mock://rent-030", "source_name": "mock", "image_url": _img("oficina", 2)},
]
