"""add sale_closings table

Revision ID: 4d9916453344
Revises: 566890867fcb
Create Date: 2026-06-07 10:00:12.246533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4d9916453344'
down_revision: Union[str, Sequence[str], None] = '566890867fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_closings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('post_visit_report_id', sa.UUID(), nullable=True),
    sa.Column('step', sa.Enum('oferta', 'negociacion', 'documentos', 'firma', 'confirmado', name='closingstep'), nullable=False),
    sa.Column('offer_price', sa.Float(), nullable=False),
    sa.Column('counter_offer_price', sa.Float(), nullable=True),
    sa.Column('agreed_price', sa.Float(), nullable=True),
    sa.Column('negotiation_message', sa.String(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('legal_summary', sa.String(), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_visit_report_id'], ['post_visit_reports.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_closing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_closings')
    # ### end Alembic commands ###
